image: nixos/nix

before_script:
  - nix-channel --add https://nixos.org/channels/nixpkgs-unstable
  - nix-channel --update
  - nix-shell --run 'cabal new-update'

build:
  stage: build
  script: nix-shell --run 'cabal new-build'
