- id: &id nixfmt
  name: *id
  entry: *id
  language: haskell
  types:
    - nix
  description: &desc The official formatter for Nix code

- id: &id-nix nixfmt-nix
  name: *id-nix
  entry: nix run github:NixOS/nixfmt
  language: system
  types:
    - nix
  description: *desc
