steps:
  - label: nix-build
    commands:
      - set -o pipefail
      - nix-build | cachix push nixfmt
      - nix-build -A cabal2nixDeriver | cachix push nixfmt
  - label: build web-demo
    commands:
      - set -o pipefail
      - nix-build release.nix -A web-demo | cachix push nixfmt
  - wait
  - label: deploy web demo
    branches: master
    commands:
      - nix-build release.nix -A web-demo --out-link /var/lib/buildkite-agent-public/cd/nixfmt-web
