name: Release on Version Change

on:
  push:
    branches:
      - master
    paths:
      - 'nixfmt.cabal'

jobs:
  release-if-version-changed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # need previous commit for comparison

      - name: Get version from nixfmt.cabal
        id: get_version
        run: |
          CABAL_FILE="nixfmt.cabal"

          # Extract the version (robustly handles whitespace)
          VERSION=$(grep -i -m1 '^[[:space:]]*version[[:space:]]*:' "$CABAL_FILE" | sed 's/.*:[[:space:]]*//')
          echo "Version found in cabal: $VERSION"

          # Get previous version from last commit
          PREV_VERSION=$(git show HEAD~1:"$CABAL_FILE" | grep -i -m1 '^[[:space:]]*version[[:space:]]*:' | sed 's/.*:[[:space:]]*//' || echo "none")
          echo "Previous version: $PREV_VERSION"

          # Export for later steps
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "prev_version=$PREV_VERSION" >> $GITHUB_OUTPUT

      - name: Check if version changed
        id: compare
        run: |
          if [ "${{ steps.get_version.outputs.version }}" != "${{ steps.get_version.outputs.prev_version }}" ]; then
            echo "version_changed=true" >> $GITHUB_ENV
            echo "✅ Version changed from ${{ steps.get_version.outputs.prev_version }} to ${{ steps.get_version.outputs.version }}"
          else
            echo "version_changed=false" >> $GITHUB_ENV
            echo "ℹ️ Version did not change — skipping release."
          fi
      - name: Extract changelog section for current version
        if: env.version_changed == 'true'
        run: |
          VERSION="${{ steps.get_version.outputs.version }}"
          echo "Extracting changelog section for version $VERSION"

          # Extract everything after the "## <version>" header until the next "## "
          awk -v ver="$VERSION" '
            $0 ~ "^##[[:space:]]+" ver {found=1; next}
            found && /^##[[:space:]]+/ {exit}
            found
          ' CHANGELOG.md > RELEASE_NOTES.md

          if [ ! -s RELEASE_NOTES.md ]; then
            echo "⚠️ No changelog section found for version $VERSION"
            echo "(Make sure you have a header like '## $VERSION -- YYYY-MM-DD')"
            echo "- No notes will be attached to the release -"
            echo "_No changelog section found for version $VERSION._" > RELEASE_NOTES.md
          fi

          echo "---- Extracted notes ----"
          cat RELEASE_NOTES.md
          echo "--------------------------"

      - name: Create Git tag
        if: env.version_changed == 'true'
        run: |
          VERSION="${{ steps.get_version.outputs.version }}"
          TAG="v${VERSION}"

          echo "Creating tag $TAG"

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git tag -a "$TAG" -m "Release $TAG"
          git push origin "$TAG"

      - name: Create GitHub Release
        if: env.version_changed == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ steps.get_version.outputs.version }}"
          name: "Release v${{ steps.get_version.outputs.version }}"
          body_path: RELEASE_NOTES.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
